version: '3'

services:
  eureka:
    build: ../../eureka/eureka
    ports:
      - 8090:8090
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://localhost:8090/eureka
  zuul:
    build: .
    ports:
      - 8092:8092
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8090/eureka
    links:
      - eureka
    depends_on:
      - eureka
  hystrixturbine:
    build: ../../Hystrix_Turbine
    ports:
      - 9090:9090
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8090/eureka
    links:
      - eureka
    depends_on:
      - eureka
      - zuul
  corerole:
    build: ../../Core_Role/Core_Role
    ports:
      - 8084:8084
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8090/eureka
    links:
      - eureka
    depends_on:
      - eureka
      - zuul
