version: '2.4'

services:
  webshop:
    build:
      context: ../../webshop_app
      dockerfile: ./Dockerfile
    ports:
      - "8888:8080"
    links: 
      - zuul
  eureka:
    build: ../../eureka/eureka
    ports:
      - 8090:8090
    environment:
      - JVM_OPTS=
        -DEUREKA_SERVER=http://localhost:8090/eureka
    mem_limit: 600m
    mem_reservation: 500m
  zuul:
    build: .
    ports:
      - 8092:8092
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8090/eureka
    links:
      - eureka
    depends_on:
      - eureka
    mem_limit: 600m
    mem_reservation: 500m
  hystrixturbine:
    build: ../../Hystrix_Turbine
    ports:
      - 9090:9090
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8090/eureka
    links:
      - eureka
      - zuul
      - coreuser
      - corerole
      - corecategory
      - coreproduct
      - compproductcategory
      - compuserrole
      - apicategory
      - apiproduct
      - apirole
      - apiuser
    depends_on:
      - eureka
      - zuul
    mem_limit: 600m
    mem_reservation: 500m
  coreuser:
    build: ../../Core_User/Core_User
    ports:
      - 8083:8083
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8761/eureka
    links:
      - eureka
    depends_on:
      - eureka
      - zuul
    mem_limit: 600m
    mem_reservation: 500m
  corerole:
    build: ../../Core_Role/Core_Role
    ports:
      - 8084:8084
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8090/eureka
    links:
      - eureka
    depends_on:
      - eureka
      - zuul
    mem_limit: 600m
    mem_reservation: 500m
  coreproduct:
    build: ../../Core_Product/Core_Product
    ports:
      - 8091:8091
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8090/eureka
    links:
      - eureka
    depends_on:
      - eureka
      - zuul
    mem_limit: 600m
    mem_reservation: 500m
  corecategory:
    build: ../../Core_Category/Core_Category
    ports:
      - 8082:8082
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8090/eureka
    links:
      - eureka
    depends_on:
      - eureka
      - zuul
    mem_limit: 600m
    mem_reservation: 500m
  compuserrole:
    build: ../../Comp_User_Role/Comp_User_Role
    ports:
      - 8085:8085
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8090/eureka
    links:
      - eureka
    depends_on:
      - eureka
      - zuul
    mem_limit: 600m
    mem_reservation: 500m
  compproductcategory:
    build: ../../Comp_Product_Category/Comp_Product_Category
    ports:
      - 8081:8081
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8090/eureka
    links:
      - eureka
    depends_on:
      - eureka
      - zuul
    mem_limit: 600m
    mem_reservation: 500m
  apiuser:
    build: ../../Api_User/Api_User
    ports:
      - 8089:8089
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8090/eureka
    links:
      - eureka
    depends_on:
      - eureka
      - zuul
    mem_limit: 600m
    mem_reservation: 500m
  apirole:
    build: ../../Api_Role/Api_Role
    ports:
      - 8088:8088
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8090/eureka
    links:
      - eureka
    depends_on:
      - eureka
      - zuul
    mem_limit: 600m
    mem_reservation: 500m
  apiproduct:
    build: ../../Api_Product/Api_Product
    ports:
      - 8087:8087
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8090/eureka
    links:
      - eureka
    depends_on:
      - eureka
      - zuul
    mem_limit: 600m
    mem_reservation: 500m
  apicategory:
    build: ../../Api_Category/Api_Category
    ports:
      - 8086:8086
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8090/eureka
    links:
      - eureka
    depends_on:
      - eureka
      - zuul
    mem_limit: 600m
    mem_reservation: 500m
